CREATE OR REPLACE PROCEDURE DEPOSITO_MONETARIA_EFECTIVO
(MONTO IN FLOAT,CTA_OR IN VARCHAR2)
IS 
V_VALIDA_CUENTA NUMBER;
V_SALDO_CUENTA CUENTA.SALDO_DISPONIBLE%TYPE;
V_BLOQUEADA CUENTA.STATUS%TYPE;
V_DIFERENCIA CUENTA.SALDO_DISPONIBLE%TYPE;
V_TIPO_CUENTA CUENTA.ID_PRODUCTO%TYPE;
BEGIN
IF(MONTO>0) THEN
--VALIDACION SI CUENTA EXISTE Y NO ESTA BLOQUEADA
	SELECT COUNT(NO_CUENTA) INTO V_VALIDA_CUENTA FROM CUENTA WHERE NO_CUENTA=CTA_OR;
	SELECT STATUS INTO V_BLOQUEADA FROM CUENTA WHERE NO_CUENTA=CTA_OR;
	IF(V_VALIDA_CUENTA=1 and V_BLOQUEADA='ACTIVO') THEN
		--VALIDACION SI ES CUENTA MONETARIA
		SELECT ID_PRODUCTO INTO V_TIPO_CUENTA FROM CUENTA WHERE NO_CUENTA=CTA_OR; --TIPO DE CUENTA ORIGEN
		IF(V_TIPO_CUENTA=2) THEN
			--VALIDACION DE SALDO
			SELECT SALDO_DISPONIBLE INTO V_SALDO_CUENTA FROM CUENTA WHERE NO_CUENTA=CTA_OR;
			V_DIFERENCIA:=V_SALDO_CUENTA+MONTO;	
			UPDATE CUENTA SET SALDO_DISPONIBLE=V_SALDO_CUENTA+MONTO, FECHA_ULTIMA_TRANSACCION=SYSDATE WHERE NO_CUENTA=CTA_OR;
			INSERT INTO OPERACION (FECHA_HORA, NO_CUENTA_ORIGEN,TIPO_OPERACION, TIPO_DOCUMENTO, NO_DOCUMENTO, STATUS, SALDO_INICIAL_ORIGEN,SALDO_FINAL_ORIGEN,MONTO_TOTAL_OPERADO,ID_CAJERO)
			VALUES (SYSDATE,CTA_OR,'DEPOSITO EN EFECTIVO','BOLETA',BOLETA.NEXTVAL,'CORRECTO',V_SALDO_CUENTA,V_DIFERENCIA,MONTO,1);
			COMMIT;
			DBMS_OUTPUT.put_line('DEPOSITO REALIZADO CORRECTAMENTE');
		ElSE
		DBMS_OUTPUT.put_line('LA CUENTA DEBE SER DE MONETARIA, FAVOR VALIDAR LOS DATOS');
		ROLLBACK;
		END IF;
	ElSE
	DBMS_OUTPUT.put_line('LA CUENTA NO EXISTE O NO ESTA ACTIVA');
	ROLLBACK;
	END IF;
ElSE
DBMS_OUTPUT.PUT_LINE('EL MONTO A DEPOSITAR NO PUEDE SER CERO');
END IF;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON DATOS, POR FAVOR VALIDE LOS DATOS');
END DEPOSITO_MONETARIA_EFECTIVO;

EXECUTE DEPOSITO_MONETARIA_EFECTIVO(100,'1-002-0000001-8');
EXECUTE DEPOSITO_MONETARIA_EFECTIVO(0,'2-001-0000001-9');
EXECUTE DEPOSITO_MONETARIA_EFECTIVO(100,'2-001-0000001-9');