DROP PROCEDURE CREAR_USUARIO;
--CREAR USUARIO
--CREAR UN NUEVO USUARIO MEDIA VEZ NO EXISTA Y EXISTA LA PERSONA Y LE ASIGNACION DE RESPONSABILIDAD POR MEDIO DEL ROL

CREATE OR REPLACE PROCEDURE CREAR_USUARIO
(   ING_DPI IN NUMBER,
    NIT IN VARCHAR2,
    NOMBRE IN VARCHAR2,
    APELLIDO IN VARCHAR2,
  	FECHA_NAC IN DATE,
  	TEL IN VARCHAR2,
  	DIR IN VARCHAR2, 
  	USERNAME IN VARCHAR2,
  	PASS IN VARCHAR2,
  	ROL IN INT)
IS
EXISTE_PERSONA NUMBER;
EXISTE_EMPLEADO NUMBER;
EXISTE_USUARIO EMPLEADO.USUARIO%TYPE;

BEGIN
    SELECT COUNT(DPI)INTO EXISTE_PERSONA FROM PERSONA WHERE DPI=ING_DPI;
    IF(EXISTE_PERSONA=1) THEN

    	SELECT COUNT(DPI)INTO EXISTE_EMPLEADO FROM EMPLEADO WHERE DPI=ING_DPI;
    	SELECT USUARIO INTO EXISTE_USUARIO FROM EMPLEADO WHERE DPI=ING_DPI;
    	
    		IF(EXISTE_EMPLEADO=0) THEN
    			INSERT INTO EMPLEADO (DPI, FECHA_ALTA, ACTIVO, USUARIO, PASSWORD, ROL) VALUES (ING_DPI,SYSDATE,'S',USERNAME,PASS,ROL);
    			COMMIT;
    			DBMS_OUTPUT.PUT_LINE('SE CREA EMPLEADO CON DPI: '||ING_DPI||'.');
    			DBMS_OUTPUT.PUT_LINE('EL USUARIO ASIGNADO ES: '||USERNAME||'.');
    		ELSE 
    			ROLLBACK;
    			DBMS_OUTPUT.PUT_LINE('EL EMPLEADO CON DPI: '||ING_DPI||' YA EXISTE');
    			DBMS_OUTPUT.PUT_LINE('TIENE EL USUARIO: '||EXISTE_USUARIO||'.');
    		END IF;
    ELSE
    	ROLLBACK;
    	DBMS_OUTPUT.PUT_LINE('LA PERSONA CON DPI: '||ING_DPI||' NO EXISTE');
    	DBMS_OUTPUT.PUT_LINE('POR FAVOR VALIDAR LOS DATOS.');    
    END IF;

END CREAR_USUARIO;

--PRUEBAS

EXECUTE CREAR_USUARIO(2951749430101,'2987564-9','LOIDA MARIA','LIMON CHUPAO','25/12/1975','23565487','28 CALLE 7-91 ZONA 3, GUATEMALA','llimon','1234',1);
EXECUTE CREAR_USUARIO(1790123400108,'2987564-9','LOIDA MARIA','LIMON CHUPAO','25/12/1975','23565487','28 CALLE 7-91 ZONA 3, GUATEMALA','llimon','1234',1);
EXECUTE CREAR_USUARIO(1234567890102,'2987564-9','LOIDA MARIA','LIMON CHUPAO','25/12/1975','23565487','28 CALLE 7-91 ZONA 3, GUATEMALA','llimon','1234',1);



DROP PROCEDURE MODIFICAR_USUARIO;
--MODIFICAR USUARIO
--INCLUYE MODIFICAR CUALQUIER CAMPO DEL USUARIO ASI COMO CABMIO DE ROL
CREATE OR REPLACE PROCEDURE MODIFICAR_USUARIO
(   V_DPI IN NUMBER,
    V_NIT IN VARCHAR2,
    V_NOMBRE IN VARCHAR2,
    V_APELLIDO IN VARCHAR2,
  	FECHA_NAC IN DATE,
  	TEL IN VARCHAR2,
  	DIR IN VARCHAR2, 
  	USERNAME IN VARCHAR2,
  	PASS IN VARCHAR2,
  	V_ROL IN INT)
IS
EXISTE_PERSONA NUMBER;
EXISTE_EMPLEADO NUMBER;
EXISTE_USUARIO EMPLEADO.USUARIO%TYPE;

BEGIN

	SELECT COUNT(DPI)INTO EXISTE_PERSONA FROM PERSONA WHERE DPI=V_DPI;
    
    IF(EXISTE_PERSONA=1) THEN
    	
    	SELECT COUNT(DPI)INTO EXISTE_EMPLEADO FROM EMPLEADO WHERE DPI=V_DPI;	
    	
    		IF(EXISTE_EMPLEADO=1) THEN
    			UPDATE PERSONA SET NIT=V_NIT, NOMBRE=V_NOMBRE, APELLIDO=V_APELLIDO, FECHA_NACIMIENTO=FECHA_NAC, NO_TELEFONO=TEL, DIRECCION=DIR WHERE DPI=V_DPI;
		    	UPDATE EMPLEADO SET USUARIO=USERNAME, PASSWORD=PASS, ROL=V_ROL WHERE DPI=V_DPI;
    			COMMIT;
    			DBMS_OUTPUT.PUT_LINE('SE ACTUALIZO EMPLEADO CON DPI: '||V_DPI||'.');

    		ELSE 
    			ROLLBACK;
    			DBMS_OUTPUT.PUT_LINE('NO EXISTE EMPLEADO CON DPI: '||V_DPI||'.');
			    DBMS_OUTPUT.PUT_LINE('POR FAVOR VALIDAR LOS DATOS.');    

    		END IF;
    ELSE
    	ROLLBACK;
    	DBMS_OUTPUT.PUT_LINE('LA PERSONA CON DPI: '||V_DPI||' NO EXISTE');
    	DBMS_OUTPUT.PUT_LINE('POR FAVOR VALIDAR LOS DATOS.');    
    END IF;

END MODIFICAR_USUARIO;

--PRUEBAS
EXECUTE MODIFICAR_USUARIO(2951749430101,'2987564-9','LOIDA MARIA','LIMON CHUPAO','25/12/1975','23565487','28 CALLE 7-91 ZONA 3, GUATEMALA','llimon','1234',1);
EXECUTE MODIFICAR_USUARIO(1790123400108,'2987564-9','LOIDA MARIA','LIMON CHUPAO','25/12/1975','23565487','28 CALLE 7-91 ZONA 3, GUATEMALA','llimon','1234',1);


DROP PROCEDURE BAJA_USUARIO;
--DAR DE BAJA A USUARIO
CREATE OR REPLACE PROCEDURE BAJA_USUARIO
(   V_DPI IN NUMBER)
IS
EXISTE_PERSONA NUMBER;
EXISTE_EMPLEADO NUMBER;

BEGIN
	SELECT COUNT(DPI)INTO EXISTE_PERSONA FROM PERSONA WHERE DPI=V_DPI;    
    IF(EXISTE_PERSONA=1) THEN    
    	SELECT COUNT(DPI)INTO EXISTE_EMPLEADO FROM EMPLEADO WHERE DPI=V_DPI;	    	
    		IF(EXISTE_EMPLEADO=1) THEN    			
		    	UPDATE EMPLEADO SET FECHA_BAJA=SYSDATE, ACTIVO='N' WHERE DPI=V_DPI;
    			COMMIT;
    			DBMS_OUTPUT.PUT_LINE('SE DIO DE BAJA AL EMPLEADO CON DPI: '||V_DPI||'.');
    		ELSE 
    			ROLLBACK;
    			DBMS_OUTPUT.PUT_LINE('NO EXISTE EMPLEADO CON DPI: '||V_DPI||'.');
			    DBMS_OUTPUT.PUT_LINE('POR FAVOR VALIDAR LOS DATOS.');
			END IF;
    ELSE
    	ROLLBACK;
    	DBMS_OUTPUT.PUT_LINE('LA PERSONA CON DPI: '||V_DPI||' NO EXISTE');
    	DBMS_OUTPUT.PUT_LINE('POR FAVOR VALIDAR LOS DATOS.');    
    END IF;
END BAJA_USUARIO;

--PRUEBAS
EXECUTE BAJA_USUARIO(2951749430101);
EXECUTE BAJA_USUARIO(1790123400108);


DROP PROCEDURE CREAR_ROL;
--CREACION DE ROLES O TIPOS DE USUARIO
CREATE OR REPLACE PROCEDURE CREAR_ROL
( V_TIPO VARCHAR2)
IS EXISTE_TIPO NUMBER;
BEGIN
	SELECT COUNT(TIPO)INTO EXISTE_TIPO FROM ROL WHERE TIPO=V_TIPO;
	IF(EXISTE_TIPO=0) THEN

		INSERT INTO ROL (TIPO) VALUES (V_TIPO);
		COMMIT;
		DBMS_OUTPUT.PUT_LINE('ROL CREADO.');
	ELSE
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('EL ROL YA EXISTE');		
	END IF;
END CREAR_ROL;

--PRUEBAS
EXECUTE CREAR_ROL('Gerente');
EXECUTE CREAR_ROL('Director');


DROP PROCEDURE SIS_LOGIN;
--LOGEO AL SISTEMA
CREATE OR REPLACE PROCEDURE SIS_LOGIN
(USERNAME VARCHAR2,
	PASS VARCHAR2)
IS EXISTE_USER NUMBER;EXISTE_PASS NUMBER; V_ID_EMP NUMBER;
BEGIN
	SELECT COUNT(USUARIO)INTO EXISTE_USER FROM EMPLEADO WHERE USUARIO=USERNAME;
	SELECT COUNT(PASSWORD)INTO EXISTE_PASS FROM EMPLEADO WHERE PASSWORD=PASS;

	IF(EXISTE_USER=1 AND EXISTE_PASS=1) THEN
			
		SELECT ID_EMPLEADO INTO V_ID_EMP FROM EMPLEADO WHERE USUARIO=USERNAME;
		INSERT INTO LOGIN (ID_EMPLEADO, FECHA_HORA) VALUES (V_ID_EMP,SYSDATE);
		COMMIT;
		DBMS_OUTPUT.PUT_LINE('LOGIN CORRECTO.');
	ELSE
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('USUARIO Y/O CONTRASEÑA INCORRECTOS');		
	END IF;
END SIS_LOGIN;

--PRUEBAS
EXECUTE SIS_LOGIN('llimon','hola');
EXECUTE SIS_LOGIN('llimon','1234');

