--------------------------------
----ASIGNACION DE NUEVA CHEQUERA
--------------------------------

DROP ASIGNAR_CHEQUERA

create or replace PROCEDURE ASIGNAR_CHEQUERA
(
	noCuenta VARCHAR2
)
IS
	existeChequera INTEGER := 0;
BEGIN
	-- Verificando que la agencia no exista
	SELECT COUNT(NO_CHEQUERA) INTO existeChequera FROM CHEQUERA WHERE NO_CUENTA=noCuenta;

	IF (existeChequera>0) THEN
		UPDATE CHEQUERA SET BLOQUEADA='S' WHERE NO_CUENTA = noCuenta;
        INSERT INTO CHEQUERA (NO_CUENTA, BLOQUEADA) VALUES (noCuenta,'N');
		COMMIT;
        DBMS_OUTPUT.PUT_LINE('NUEVA CHEQUERA ASIGNADA');
	ELSE
    	ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('NO SE PUDO ASIGNAR CHEQUERA');
	END IF;
END ASIGNAR_CHEQUERA;

----------------------
---- ASIGNAR LIBRETA
-----------------------

DROP PROCEDURE ASIGNAR_LIBRETA;

create or replace PROCEDURE ASIGNAR_LIBRETA
(
	noCuenta VARCHAR2
)
IS
	existeLibreta INTEGER := 0;
BEGIN
	-- Verificando que la agencia no exista
	SELECT COUNT(NO_LIBRETA) INTO existeLibreta FROM LIBRETA WHERE NO_CUENTA=noCuenta;

	IF (existeLibreta>0) THEN
		UPDATE LIBRETA SET ESTADO='CANCELADA' WHERE NO_CUENTA = noCuenta;
        INSERT INTO LIBRETA (NO_CUENTA, ESTADO, FECHA_ASIGNACION, FECHA_VENCIMIENTO) VALUES (noCuenta,'ACTIVA', SYSDATE,SYSDATE+1);
		COMMIT;
        DBMS_OUTPUT.PUT_LINE('NUEVA LIBRETA ASIGNADA');
	ELSE
    	ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('NO SE PUDO ASIGNAR LIBRETA');
	END IF;
END ASIGNAR_LIBRETA;