CREATE OR REPLACE VIEW  "ESTADO_CUENTA" AS 
(SELECT b.TIPO_OPERACION, a.NO_CUENTA, (SELECT CONCAT(d.NOMBRE,d.APELLIDO) FROM PERSONA d WHERE d.DPI = c.DPI) AS "NOMBRE", 
(SELECT e.NOMBRE FROM EMPRESA e WHERE e.ID_PATENTE=c.ID_PATENTE) AS "EMPRESA", b.STATUS,
 (CASE WHEN a.NO_CUENTA = b.NO_CUENTA_ORIGEN THEN b.SALDO_INICIAL_ORIGEN ELSE NULL END)  AS "SALDO_INICIAL",
 MONTO_TOTAL_OPERADO AS "MONTO",
(CASE WHEN a.NO_CUENTA = b.NO_CUENTA_ORIGEN THEN b.SALDO_FINAL_ORIGEN ELSE NULL END)  AS "SALDO_FINAL",
expresar_en_letras.numero_a_letras(CASE WHEN a.NO_CUENTA = b.NO_CUENTA_ORIGEN THEN b.SALDO_FINAL_ORIGEN ELSE NULL END)  AS "En_letras",
b.TIPO_DOCUMENTO, b.FECHA_HORA,
(SELECT h.NOMBRE FROM AGENCIA h WHERE h.ID_AGENCIA = g.ID_AGENCIA) AS "AGENCIA",
(SELECT j.USUARIO FROM EMPLEADO j WHERE f.ID_EMPLEADO=j.ID_EMPLEADO) AS "USUARIO" FROM CUENTA a
INNER JOIN CLIENTE c ON c.ID_CLIENTE=a.ID_CLIENTE
INNER JOIN OPERACION b ON a.NO_CUENTA = b.NO_CUENTA_ORIGEN
INNER JOIN CAJERO f ON b.ID_CAJERO = f.ID_CAJERO
INNER JOIN CAJA g ON f.ID_CAJA = g.ID_CAJA);