DROP TRIGGER CUENTA_NEGATIVO;
DROP TRIGGER OPERACIONES_SALDOS_NEGATIVO;
DROP TRIGGER RECARGO_NEGATIVO;
DROP TRIGGER PLANILLA_NEGATIVO;


--VALIDAR QUE EL ESTADO DE UNA CUENTA NO PUEDE QUEDAR CON VALOR NEGATIVO
CREATE OR REPLACE TRIGGER CUENTA_NEGATIVO
BEFORE INSERT OR UPDATE ON CUENTA
FOR EACH ROW

DECLARE
SALDO NUMBER:=0;
RESERVA NUMBER:=0;
BEGIN
    SALDO := :NEW.SALDO_DISPONIBLE;
    RESERVA := :NEW.SALDO_RESERVA;
    IF (SALDO<0) THEN
        raise_application_error(-20000, ' La cuenta no puede quedar negarivo. ' || SALDO);
    END IF;
    
    IF (RESERVA<0) THEN
        raise_application_error(-20000, ' El saldo reserva no puede quedar negarivo. ' || RESERVA);
    END IF;
END;

--VALIDAR QUE LOS SALDOS DE OPERACIONES NO QUEDEN NEGATIVOS 
CREATE OR REPLACE TRIGGER OPERACIONES_SALDOS_NEGATIVO
BEFORE INSERT OR UPDATE ON OPERACION
FOR EACH ROW

DECLARE
SALDO_INICIAL_O NUMBER:=0;
SALDO_FINAL_O NUMBER:=0;
SALDO_INICIAL_D NUMBER:=0;
SALDO_FINAL_D NUMBER:=0;
MONTO_TOTAL NUMBER:=0;

BEGIN
    SALDO_INICIAL_O := :NEW.SALDO_INICIAL_ORIGEN;
    SALDO_FINAL_O := :NEW.SALDO_FINAL_ORIGEN;
    SALDO_INICIAL_D := :NEW.SALDO_INICIAL_DESTINO;
    SALDO_FINAL_D := :NEW.SALDO_FINAL_DESTINO;
    MONTO_TOTAL := :NEW.MONTO_TOTAL_OPERADO;
    IF (SALDO_INICIAL_O<0)or(SALDO_FINAL_O<0)or (SALDO_INICIAL_D<0)or(SALDO_FINAL_D<0) or (MONTO_TOTAL<0) THEN
        raise_application_error(-20000, ' Cualquier saldo no puede quedar negativo. ' || SALDO_INICIAL_O || ', ' || SALDO_FINAL_O || ', ' || SALDO_INICIAL_D || ', ' ||SALDO_FINAL_D|| ', ' || MONTO_TOTAL);
    END IF;
END;


--VALIDAR QUE LOS RECARGOS NO PUEDEN SER NEGATIVOS
CREATE OR REPLACE TRIGGER RECARGO_NEGATIVO
BEFORE INSERT OR UPDATE ON RECARGO
FOR EACH ROW

DECLARE
RECAR NUMBER:=0;

BEGIN
    RECAR := :NEW.RECARGO;
    IF (RECAR<0) THEN
        raise_application_error(-20000, ' Los recargos no pueden quedar negativos. ' || RECAR);
    END IF;
END;

--VALIDAR EL MONTO TOTAL A OPERAR DE UNA PLANILLA NO QUEDE NEGATIVO
CREATE OR REPLACE TRIGGER PLANILLA_NEGATIVO
BEFORE INSERT OR UPDATE ON OPERACION_PLANILLA
FOR EACH ROW

DECLARE
OPERACION_PLANILLA NUMBER:=0;

BEGIN
    OPERACION_PLANILLA := :NEW.TOTAL_PAGADO;
    IF (OPERACION_PLANILLA<0) THEN
        raise_application_error(-20000, 'El total a transferir no puede ser negativo. ' || OPERACION_PLANILLA);
    END IF;
END;